"""Generate every rendering of the ServoMap mark from one geometry.

The mark is a semicircular fuel gauge: radial ticks generated by `geometry()`,
a vermilion needle, and a fuel drop under the pivot. Colours are not owned here:
they come from `markColor` in packages/design-tokens/src/tokens.ts, read through
the generated packages/design-tokens/generated/tokens.json.

Outputs (all generated, never hand-edited):
  design/app-icon/ServoMap.icon                  Icon Composer bundle (iOS app icon)
  packages/web/src/app/icon.svg                  favicon
  packages/web/src/components/brand/mark.ts      geometry for the header logo and OG images

Run from the repository root, after `pnpm --filter @servo-map/design-tokens generate`:
  python3 design/app-icon/generate.py            rewrite every output
  python3 design/app-icon/generate.py --check    fail if any output is stale (CI)
"""

import json
import math
import pathlib
import sys
from dataclasses import dataclass

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]
WEB = ROOT / "packages" / "web" / "src"
TOKENS = ROOT / "packages" / "design-tokens" / "generated" / "tokens.json"
BUNDLE = HERE / "ServoMap.icon"
FAVICON = WEB / "app" / "icon.svg"
MARK_TS = WEB / "components" / "brand" / "mark.ts"
GENERATED = "Generated by design/app-icon/generate.py; do not edit by hand."

CX, CY, RADIUS = 512, 600, 330
TICKS, MAJOR_EVERY = 25, 6
MAJOR, MINOR = (62, 14), (30, 10)  # (length, stroke width)
NEEDLE_WIDTH, PIVOT = 22, 26
DROP_SCALE, DROP_OFFSET = 4.6, 118  # drop size; pivot to the drop's round-part centre
LEVEL = 0.72  # needle position across the sweep
TILE_RADIUS = 224  # web tile corner, matching the iOS squircle's visual weight


@dataclass(frozen=True)
class Themed:
    """One colour for the light appearance and one for the dark."""

    light: str
    dark: str


@dataclass(frozen=True)
class Palette:
    """The mark's colours, as the design tokens assign them."""

    tile: Themed
    ink: Themed
    accent: Themed


def load_palette() -> Palette:
    """Read `markColor` from the design tokens' JSON export."""
    mark = json.loads(TOKENS.read_text())["mark"]
    return Palette(**{role: Themed(**mark[role]) for role in ("tile", "ink", "accent")})


@dataclass(frozen=True)
class Geometry:
    """Path data for the mark on a 1024-unit canvas, before centring."""

    ticks: dict[float, str]  # stroke width -> path data of every tick that width
    drop: str
    needle: str
    pivot: tuple[float, float, float]  # cx, cy, r
    bounds: tuple[float, float, float, float]  # x0, y0, x1, y1 of everything drawn


def _bounds(
    discs: list[tuple[float, float, float]],
) -> tuple[float, float, float, float]:
    """Box around discs (x, y, r); a round-capped stroke is covered by discs at its two ends."""
    return (
        min(x - r for x, _, r in discs),
        min(y - r for _, y, r in discs),
        max(x + r for x, _, r in discs),
        max(y + r for _, y, r in discs),
    )


def _drop_path(cx: float, cy: float, s: float) -> str:
    """Teardrop whose round part is centred on (cx, cy)."""
    top = cy - 13.9 * s
    return (
        f"M{cx:.1f} {top:.1f}c{5 * s:.1f} {6.8 * s:.1f} {7 * s:.1f} {10.8 * s:.1f} {7 * s:.1f} {13.9 * s:.1f}"
        f"a{7 * s:.1f} {7 * s:.1f} 0 1 1 {-14 * s:.1f} 0c0 {-3.1 * s:.1f} {2 * s:.1f} {-7.1 * s:.1f} {7 * s:.1f} {-13.9 * s:.1f}Z"
    )


def geometry() -> Geometry:
    """Build the gauge; fails loudly if any two ticks' inner ends crowd each other."""
    step = math.pi / (TICKS - 1)
    ticks: dict[float, list[str]] = {}
    discs: list[tuple[float, float, float]] = []
    for i in range(TICKS):
        length, width = MAJOR if i % MAJOR_EVERY == 0 else MINOR
        if (RADIUS - length) * step - width < width:
            raise ValueError(f"tick {i}: inner gap narrower than its stroke")
        a = math.pi - step * i
        cos_a, sin_a = math.cos(a), math.sin(a)
        inner = RADIUS - length
        for r in (RADIUS, inner):
            discs.append((CX + r * cos_a, CY - r * sin_a, width / 2))
        ticks.setdefault(width, []).append(
            f"M{CX + RADIUS * cos_a:.1f} {CY - RADIUS * sin_a:.1f}"
            f"L{CX + inner * cos_a:.1f} {CY - inner * sin_a:.1f}"
        )
    a = math.pi * (1 - LEVEL)
    reach = RADIUS - MAJOR[0] - 48  # clear of the longest tick
    tip = (CX + reach * math.cos(a), CY - reach * math.sin(a))
    needle = f"M{CX} {CY}L{tip[0]:.1f} {tip[1]:.1f}"
    drop_y, drop_r = CY + DROP_OFFSET, 7 * DROP_SCALE
    discs += [
        (*tip, NEEDLE_WIDTH / 2),
        (CX, CY, PIVOT),
        (CX, drop_y, drop_r),  # the drop's round part
        (CX, drop_y - 13.9 * DROP_SCALE, 0),  # the drop's point
    ]
    return Geometry(
        ticks={w: "".join(d) for w, d in ticks.items()},
        drop=_drop_path(CX, CY + DROP_OFFSET, DROP_SCALE),
        needle=needle,
        pivot=(CX, CY, PIVOT),
        bounds=_bounds(discs),
    )


def _stroke(d: str, width: float, ink: str) -> str:
    return f'<path d="{d}" fill="none" stroke="{ink}" stroke-width="{width}" stroke-linecap="round"/>'


def gauge_svg(g: Geometry, ink: str = "#fff") -> str:
    ticks = "".join(_stroke(d, w, ink) for w, d in g.ticks.items())
    return ticks + f'<path d="{g.drop}" fill="{ink}"/>'


def needle_svg(g: Geometry, ink: str = "#fff") -> str:
    cx, cy, r = g.pivot
    return (
        _stroke(g.needle, NEEDLE_WIDTH, ink)
        + f'<circle cx="{cx}" cy="{cy}" r="{r}" fill="{ink}"/>'
    )


def _canvas(inner: str, shift: tuple[float, float]) -> str:
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">'
        f'<g transform="translate({shift[0]:.1f} {shift[1]:.1f})">{inner}</g></svg>\n'
    )


def centring_shift(g: Geometry) -> tuple[float, float]:
    """Centre the whole mark's exact bounding box on the canvas.

    Measured from the geometry rather than a rasterisation, so --check recomputes it with
    no external tools and a change to the geometry or to this function shows up as drift.
    """
    x0, y0, x1, y1 = g.bounds
    return round(512 - (x0 + x1) / 2, 1), round(512 - (y0 + y1) / 2, 1)


def _colour(hex_: str, alpha: float = 1.0) -> str:
    r, g, b = (int(hex_[i : i + 2], 16) / 255 for i in (1, 3, 5))
    return f"extended-srgb:{r:.5f},{g:.5f},{b:.5f},{alpha:.5f}"


def _group(name: str, image: str, light: str, dark: str, tinted_alpha: float) -> dict:
    return {
        "name": name,
        "lighting": "individual",
        "specular": True,
        "shadow": {"kind": "neutral", "opacity": 0.08},
        "translucency": {"enabled": False, "value": 0},
        "layers": [
            {
                "name": name,
                "image-name": image,
                "glass": True,
                "fill-specializations": [
                    {"value": {"solid": _colour(light)}},
                    {"appearance": "dark", "value": {"solid": _colour(dark)}},
                    {
                        "appearance": "tinted",
                        "value": {"solid": _colour("#FFFFFF", tinted_alpha)},
                    },
                ],
            }
        ],
    }


def app_icon_files(
    g: Geometry, shift: tuple[float, float], p: Palette
) -> dict[pathlib.Path, str]:
    icon = {
        "fill-specializations": [
            {"value": {"solid": _colour(p.tile.light)}},
            {"appearance": "dark", "value": {"solid": _colour(p.tile.dark)}},
        ],
        "groups": [  # first group is frontmost
            _group("Needle", "needle.svg", p.accent.light, p.accent.dark, 1.0),
            _group("Gauge", "gauge.svg", p.ink.light, p.ink.dark, 0.9),
        ],
        "supported-platforms": {"circles": ["watchOS"], "squares": "shared"},
    }
    return {
        BUNDLE / "Assets" / "gauge.svg": _canvas(gauge_svg(g), shift),
        BUNDLE / "Assets" / "needle.svg": _canvas(needle_svg(g), shift),
        BUNDLE / "icon.json": json.dumps(icon, indent=2) + "\n",
    }


def favicon(g: Geometry, shift: tuple[float, float], p: Palette) -> str:
    """Light tile in light mode, dark tile in dark mode, like the app icon's two appearances."""
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">\n'
        f"  <!-- {GENERATED} -->\n"
        f"  <style>.tile{{fill:{p.tile.light}}}.ink{{color:{p.ink.light}}}.shu{{color:{p.accent.light}}}"
        f"@media (prefers-color-scheme:dark){{.tile{{fill:{p.tile.dark}}}.ink{{color:{p.ink.dark}}}.shu{{color:{p.accent.dark}}}}}</style>\n"
        f'  <rect class="tile" width="1024" height="1024" rx="{TILE_RADIUS}"/>\n'
        f'  <g transform="translate({shift[0]} {shift[1]})">\n'
        f'    <g class="ink">{gauge_svg(g, "currentColor")}</g>\n'
        f'    <g class="shu">{needle_svg(g, "currentColor")}</g>\n'
        "  </g>\n"
        "</svg>\n"
    )


def mark_ts(g: Geometry, shift: tuple[float, float]) -> str:
    ticks = ",\n".join(f'  {{ d: "{d}", width: {w} }}' for w, d in g.ticks.items())
    cx, cy, r = g.pivot
    return (
        f"// {GENERATED}\n"
        "// Path data for the ServoMap fuel-gauge mark on a 1024-unit canvas.\n"
        "// Its colours are `markColor` in @servo-map/design-tokens.\n\n"
        'export const MARK_VIEWBOX = "0 0 1024 1024";\n'
        f"export const MARK_TILE_RADIUS = {TILE_RADIUS};\n"
        f'export const MARK_TRANSFORM = "translate({shift[0]} {shift[1]})";\n\n'
        f"export const MARK_TICKS = [\n{ticks},\n] as const;\n\n"
        f'export const MARK_DROP = "{g.drop}";\n'
        f'export const MARK_NEEDLE = {{ d: "{g.needle}", width: {NEEDLE_WIDTH} }} as const;\n'
        f"export const MARK_PIVOT = {{ cx: {cx}, cy: {cy}, r: {r} }} as const;\n"
    )


def outputs() -> dict[pathlib.Path, str]:
    """Every generated file and its content."""
    g = geometry()
    shift = centring_shift(g)
    palette = load_palette()
    return {
        **app_icon_files(g, shift, palette),
        FAVICON: favicon(g, shift, palette),
        MARK_TS: mark_ts(g, shift),
    }


def check() -> int:
    """Exit status 1, naming each file, when a committed output differs from a fresh render."""
    stale = [
        path
        for path, content in outputs().items()
        if not path.exists() or path.read_text() != content
    ]
    for path in stale:
        print(f"stale: {path.relative_to(ROOT)}", file=sys.stderr)
    if stale:
        print("Run: python3 design/app-icon/generate.py", file=sys.stderr)
    return 1 if stale else 0


def main() -> None:
    if sys.argv[1:] == ["--check"]:
        sys.exit(check())
    for path, content in outputs().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


if __name__ == "__main__":
    main()
