"""Generate every rendering of the ServoMap mark from one geometry.

The mark is a semicircular fuel gauge: radial ticks generated by `geometry()`,
a vermilion needle, and a fuel drop under the pivot. Colours follow the
web palette (washi paper / sumi ink) with one vermilion accent.

Outputs (all generated, never hand-edited):
  design/app-icon/ServoMap.icon                  Icon Composer bundle (iOS app icon)
  packages/web/src/app/icon.svg                  favicon
  packages/web/src/components/brand/mark.ts      geometry for the header logo and OG images

Run from the repository root:  python3 design/app-icon/generate.py
"""

import json
import math
import pathlib
import subprocess
from dataclasses import dataclass

HERE = pathlib.Path(__file__).resolve().parent
WEB = HERE.parents[1] / "packages" / "web" / "src"
BUNDLE = HERE / "ServoMap.icon"
FAVICON = WEB / "app" / "icon.svg"
MARK_TS = WEB / "components" / "brand" / "mark.ts"
GENERATED = "Generated by design/app-icon/generate.py; do not edit by hand."

PAPER, PAPER_INK = "#F3EEE6", "#E9E3D9"  # light background / dark-mode ink
SUMI, SUMI_BG = "#2A2723", "#151412"  # light-mode ink / dark background
SHU, SHU_DARK = "#C25E3A", "#D9764F"  # vermilion = web terracotta-dim

CX, CY, RADIUS = 512, 600, 330
TICKS, MAJOR_EVERY = 25, 6
MAJOR, MINOR = (62, 14), (30, 10)  # (length, stroke width)
NEEDLE_WIDTH, PIVOT = 22, 26
DROP_SCALE, DROP_OFFSET = 4.6, 118  # drop size; pivot to the drop's round-part centre
LEVEL = 0.72  # needle position across the sweep
TILE_RADIUS = 224  # web tile corner, matching the iOS squircle's visual weight


@dataclass(frozen=True)
class Geometry:
    """Path data for the mark on a 1024-unit canvas, before centring."""

    ticks: dict[float, str]  # stroke width -> path data of every tick that width
    drop: str
    needle: str
    pivot: tuple[float, float, float]  # cx, cy, r


def _drop_path(cx: float, cy: float, s: float) -> str:
    """Teardrop whose round part is centred on (cx, cy)."""
    top = cy - 13.9 * s
    return (
        f"M{cx:.1f} {top:.1f}c{5 * s:.1f} {6.8 * s:.1f} {7 * s:.1f} {10.8 * s:.1f} {7 * s:.1f} {13.9 * s:.1f}"
        f"a{7 * s:.1f} {7 * s:.1f} 0 1 1 {-14 * s:.1f} 0c0 {-3.1 * s:.1f} {2 * s:.1f} {-7.1 * s:.1f} {7 * s:.1f} {-13.9 * s:.1f}Z"
    )


def geometry() -> Geometry:
    """Build the gauge; fails loudly if any two ticks' inner ends crowd each other."""
    step = math.pi / (TICKS - 1)
    ticks: dict[float, list[str]] = {}
    for i in range(TICKS):
        length, width = MAJOR if i % MAJOR_EVERY == 0 else MINOR
        if (RADIUS - length) * step - width < width:
            raise ValueError(f"tick {i}: inner gap narrower than its stroke")
        a = math.pi - step * i
        cos_a, sin_a = math.cos(a), math.sin(a)
        inner = RADIUS - length
        ticks.setdefault(width, []).append(
            f"M{CX + RADIUS * cos_a:.1f} {CY - RADIUS * sin_a:.1f}"
            f"L{CX + inner * cos_a:.1f} {CY - inner * sin_a:.1f}"
        )
    a = math.pi * (1 - LEVEL)
    reach = RADIUS - MAJOR[0] - 48  # clear of the longest tick
    needle = f"M{CX} {CY}L{CX + reach * math.cos(a):.1f} {CY - reach * math.sin(a):.1f}"
    return Geometry(
        ticks={w: "".join(d) for w, d in ticks.items()},
        drop=_drop_path(CX, CY + DROP_OFFSET, DROP_SCALE),
        needle=needle,
        pivot=(CX, CY, PIVOT),
    )


def _stroke(d: str, width: float, ink: str) -> str:
    return f'<path d="{d}" fill="none" stroke="{ink}" stroke-width="{width}" stroke-linecap="round"/>'


def gauge_svg(g: Geometry, ink: str = "#fff") -> str:
    ticks = "".join(_stroke(d, w, ink) for w, d in g.ticks.items())
    return ticks + f'<path d="{g.drop}" fill="{ink}"/>'


def needle_svg(g: Geometry, ink: str = "#fff") -> str:
    cx, cy, r = g.pivot
    return (
        _stroke(g.needle, NEEDLE_WIDTH, ink)
        + f'<circle cx="{cx}" cy="{cy}" r="{r}" fill="{ink}"/>'
    )


def _canvas(inner: str, shift: tuple[float, float]) -> str:
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">'
        f'<g transform="translate({shift[0]:.1f} {shift[1]:.1f})">{inner}</g></svg>\n'
    )


def centring_shift(g: Geometry) -> tuple[float, float]:
    """Optically centre the whole mark: rasterise it in white and measure its bounding box."""
    probe = HERE / ".probe.svg"
    png = probe.with_suffix(".png")
    probe.write_text(_canvas(gauge_svg(g) + needle_svg(g), (0, 0)))
    try:
        subprocess.run(["rsvg-convert", "-b", "black", probe, "-o", png], check=True)
        box = subprocess.run(
            ["magick", png, "-trim", "-format", "%w %h %X %Y", "info:"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.split()
    finally:
        probe.unlink(missing_ok=True)
        png.unlink(missing_ok=True)
    w, h, x, y = map(int, box)
    return round(512 - (x + w / 2), 1), round(512 - (y + h / 2), 1)


def _colour(hex_: str, alpha: float = 1.0) -> str:
    r, g, b = (int(hex_[i : i + 2], 16) / 255 for i in (1, 3, 5))
    return f"extended-srgb:{r:.5f},{g:.5f},{b:.5f},{alpha:.5f}"


def _group(name: str, image: str, light: str, dark: str, tinted_alpha: float) -> dict:
    return {
        "name": name,
        "lighting": "individual",
        "specular": True,
        "shadow": {"kind": "neutral", "opacity": 0.08},
        "translucency": {"enabled": False, "value": 0},
        "layers": [
            {
                "name": name,
                "image-name": image,
                "glass": True,
                "fill-specializations": [
                    {"value": {"solid": _colour(light)}},
                    {"appearance": "dark", "value": {"solid": _colour(dark)}},
                    {
                        "appearance": "tinted",
                        "value": {"solid": _colour("#FFFFFF", tinted_alpha)},
                    },
                ],
            }
        ],
    }


def write_app_icon(g: Geometry, shift: tuple[float, float]) -> None:
    (BUNDLE / "Assets").mkdir(parents=True, exist_ok=True)
    (BUNDLE / "Assets" / "gauge.svg").write_text(_canvas(gauge_svg(g), shift))
    (BUNDLE / "Assets" / "needle.svg").write_text(_canvas(needle_svg(g), shift))
    icon = {
        "fill-specializations": [
            {"value": {"solid": _colour(PAPER)}},
            {"appearance": "dark", "value": {"solid": _colour(SUMI_BG)}},
        ],
        "groups": [  # first group is frontmost
            _group("Needle", "needle.svg", SHU, SHU_DARK, 1.0),
            _group("Gauge", "gauge.svg", SUMI, PAPER_INK, 0.9),
        ],
        "supported-platforms": {"circles": ["watchOS"], "squares": "shared"},
    }
    (BUNDLE / "icon.json").write_text(json.dumps(icon, indent=2) + "\n")


def write_favicon(g: Geometry, shift: tuple[float, float]) -> None:
    """Paper tile in light mode, sumi tile in dark mode, like the app icon's two appearances."""
    FAVICON.write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">\n'
        f"  <!-- {GENERATED} -->\n"
        f"  <style>.tile{{fill:{PAPER}}}.ink{{color:{SUMI}}}.shu{{color:{SHU}}}"
        f"@media (prefers-color-scheme:dark){{.tile{{fill:{SUMI_BG}}}.ink{{color:{PAPER_INK}}}.shu{{color:{SHU_DARK}}}}}</style>\n"
        f'  <rect class="tile" width="1024" height="1024" rx="{TILE_RADIUS}"/>\n'
        f'  <g transform="translate({shift[0]} {shift[1]})">\n'
        f'    <g class="ink">{gauge_svg(g, "currentColor")}</g>\n'
        f'    <g class="shu">{needle_svg(g, "currentColor")}</g>\n'
        "  </g>\n"
        "</svg>\n"
    )


def write_mark_ts(g: Geometry, shift: tuple[float, float]) -> None:
    ticks = ",\n".join(f'  {{ d: "{d}", width: {w} }}' for w, d in g.ticks.items())
    cx, cy, r = g.pivot
    MARK_TS.parent.mkdir(parents=True, exist_ok=True)
    MARK_TS.write_text(
        f"// {GENERATED}\n"
        "// Path data for the ServoMap fuel-gauge mark on a 1024-unit canvas.\n\n"
        'export const MARK_VIEWBOX = "0 0 1024 1024";\n'
        f"export const MARK_TILE_RADIUS = {TILE_RADIUS};\n"
        f'export const MARK_TRANSFORM = "translate({shift[0]} {shift[1]})";\n\n'
        f"export const MARK_TICKS = [\n{ticks},\n] as const;\n\n"
        f'export const MARK_DROP = "{g.drop}";\n'
        f'export const MARK_NEEDLE = {{ d: "{g.needle}", width: {NEEDLE_WIDTH} }} as const;\n'
        f"export const MARK_PIVOT = {{ cx: {cx}, cy: {cy}, r: {r} }} as const;\n\n"
        "export const MARK_COLORS = {\n"
        f'  light: {{ tile: "{PAPER}", ink: "{SUMI}", accent: "{SHU}" }},\n'
        f'  dark: {{ tile: "{SUMI_BG}", ink: "{PAPER_INK}", accent: "{SHU_DARK}" }},\n'
        "} as const;\n"
    )


def main() -> None:
    g = geometry()
    shift = centring_shift(g)
    write_app_icon(g, shift)
    write_favicon(g, shift)
    write_mark_ts(g, shift)


if __name__ == "__main__":
    main()
