import { color, markColor } from "./tokens";

/**
 * Colour tokens as JSON, for consumers outside TypeScript (design/app-icon/generate.py).
 * JSON has no comments, so the provenance note is a `$generated` key.
 */
export function emitJson(): string {
  const doc = {
    $generated: "Generated by @servo-map/design-tokens (scripts/generate.ts) from src/tokens.ts. Do not edit.",
    color,
    mark: markColor,
  };
  return `${JSON.stringify(doc, null, 2)}\n`;
}
