import { color, font, motion, radius, space, text } from "./tokens";

function hex(value: string): string {
  return `0x${value.slice(1).toUpperCase()}`;
}

/** Default point size of each iOS text style at the standard Dynamic Type setting. */
const IOS_SIZES = {
  caption2: 11,
  caption: 12,
  footnote: 13,
  subheadline: 15,
  body: 17,
  title3: 20,
  title2: 22,
  largeTitle: 34,
} as const;

/** SwiftUI weight for a web weight, for faces the system draws. */
const SYSTEM_WEIGHTS = { 400: "regular", 500: "medium", 600: "semibold", 700: "bold" } as const;

/** A role's face for one weight: a bundled font, or the system font at that weight. */
function styleFont(role: keyof typeof font, weight: 400 | 500 | 600 | 700, style: string, size: number): string {
  const faces = font[role].ios;
  return faces === "system"
    ? `Font.system(.${style}, weight: .${SYSTEM_WEIGHTS[weight]})`
    : `Font.custom("${faces[weight]}", size: ${size}, relativeTo: .${style})`;
}

/** Swift for `display(...)` or `body(...)` and its face lookup. */
function roleFunctions(role: keyof typeof font, fn: string, doc: string, fallback: 400 | 600): string {
  const faces = font[role].ios;
  if (faces === "system") {
    const cases = Object.entries(SYSTEM_WEIGHTS).map(([w, name]) => `        case ${w}: .${name}`).join("\n");
    return `    /** ${doc} */
    public static func ${fn}(_ style: Font.TextStyle, weight: Int = ${fallback}, size: CGFloat? = nil) -> Font {
        size.map { .system(size: $0, weight: ${fn}Weight(weight)) } ?? .system(style, weight: ${fn}Weight(weight))
    }

    public static func ${fn}Weight(_ weight: Int) -> Font.Weight {
        switch weight {
${cases}
        default: .${SYSTEM_WEIGHTS[fallback]}
        }
    }`;
  }
  const cases = Object.entries(faces).map(([w, ps]) => `            case ${w}: "${ps}"`).join("\n");
  return `    /** ${doc} */
    public static func ${fn}(_ style: Font.TextStyle, weight: Int = ${fallback}, size: CGFloat? = nil) -> Font {
        .custom(${fn}Face(weight), size: size ?? pointSize(style), relativeTo: style)
    }

    public static func ${fn}Face(_ weight: Int) -> String {
        switch weight {
${cases}
            default: "${faces[fallback]}"
        }
    }`;
}

/** SwiftUI source for the iOS app, vendored from this package. */
export function emitSwift(): string {
  const colors = Object.entries(color).map(
    ([name, v]) => `    public static let ${name} = Color(light: ${hex(v.light)}, dark: ${hex(v.dark)})`,
  );
  const spaces = space.map((px, i) => `    public static let x${i + 1}: CGFloat = ${px}`);
  const radii = Object.entries(radius).map(([name, px]) => `    public static let ${name}: CGFloat = ${px}`);
  // iOS keeps its own type sizes: each step uses the system size of its text style and scales with Dynamic Type.
  const styles = Object.entries(text).map(
    ([name, s]) =>
      `    public static let ${name} = ${styleFont(s.font, s.weight, s.ios, IOS_SIZES[s.ios])}`,
  );
  const [x1, y1, x2, y2] = motion.easing;

  return `// Generated by @servo-map/design-tokens (scripts/generate.ts) from src/tokens.ts. Do not edit.
// Vendor this file into the iOS app unchanged; regenerate instead of editing.
// These tokens style content. Bars, sheets and floating controls use the system
// Liquid Glass material (iOS 27), tinted with ServoMapColor.accent at most.

import SwiftUI
#if canImport(UIKit)
import UIKit
#endif

public enum ServoMapColor {
${colors.join("\n")}
}

public enum ServoMapSpace {
${spaces.join("\n")}
}

public enum ServoMapRadius {
${radii.join("\n")}
}

public enum ServoMapFont {
${styles.join("\n")}

${roleFunctions("display", "display", "Mincho for headings and prices, at a text style's size and a web weight (400–700).", 600)}

${roleFunctions("body", "body", "Interface text, at a text style's size and a web weight (400–700).", 400)}

    static func pointSize(_ style: Font.TextStyle) -> CGFloat {
        switch style {
        case .largeTitle: 34
        case .title: 28
        case .title2: 22
        case .title3: 20
        case .headline, .body: 17
        case .callout: 16
        case .subheadline: 15
        case .footnote: 13
        case .caption: 12
        default: 11
        }
    }
}

public enum ServoMapMotion {
    public static let fast: Double = ${motion.durationMs.fast / 1000}
    public static let normal: Double = ${motion.durationMs.normal / 1000}
    public static let slow: Double = ${motion.durationMs.slow / 1000}
    public static let riseDistance: CGFloat = ${motion.riseDistance}
    public static let standard = Animation.timingCurve(${x1}, ${y1}, ${x2}, ${y2}, duration: normal)
    /** Switching between sub-pages under a segmented bar: the system's snappy spring at the slow duration. */
    public static let snappy = Animation.snappy(duration: slow)
}

extension Color {
    /** A colour that follows the system light/dark appearance. */
    init(light: UInt32, dark: UInt32) {
        #if canImport(UIKit)
        self.init(uiColor: UIColor { traits in
            UIColor(rgb: traits.userInterfaceStyle == .dark ? dark : light)
        })
        #else
        self.init(red: Double((light >> 16) & 0xFF) / 255, green: Double((light >> 8) & 0xFF) / 255, blue: Double(light & 0xFF) / 255)
        #endif
    }
}

#if canImport(UIKit)
extension UIColor {
    convenience init(rgb: UInt32) {
        self.init(
            red: CGFloat((rgb >> 16) & 0xFF) / 255,
            green: CGFloat((rgb >> 8) & 0xFF) / 255,
            blue: CGFloat(rgb & 0xFF) / 255,
            alpha: 1
        )
    }
}
#endif
`;
}
