import { kebab } from "./case";
import { color, font, motion, radius, shadowFloat, text, type ThemeColor } from "./tokens";

const HEADER =
  "/* Generated by @servo-map/design-tokens (scripts/generate.ts) from src/tokens.ts. Do not edit. */";

function fontStack(role: keyof typeof font): string {
  const { family, fallback } = font[role];
  const quoted = fallback.map((f) => (f.includes(" ") ? `"${f}"` : f));
  // next/font sets --font-loaded-<role> on <html>; the literal family covers a system install.
  return [`var(--font-loaded-${role}, "${family}")`, ...quoted].join(", ");
}

function colorLines(theme: keyof ThemeColor): string[] {
  return Object.entries(color).map(
    ([name, value]) => `  --color-${kebab(name)}: ${value[theme]};`,
  );
}

/** Tailwind 4 `@theme` block (light values) plus the dark-theme override. */
export function emitCss(): string {
  const [x1, y1, x2, y2] = motion.easing;
  const theme = [
    ...colorLines("light"),
    "",
    `  --font-display: ${fontStack("display")};`,
    `  --font-body: ${fontStack("body")};`,
    "",
    ...Object.entries(text).flatMap(([name, s]) => [
      `  --text-${kebab(name)}: ${s.size}px;`,
      `  --text-${kebab(name)}--line-height: ${s.lineHeight};`,
      `  --text-${kebab(name)}--letter-spacing: ${s.tracking}em;`,
    ]),
    "",
    ...Object.entries(radius).map(([name, px]) => `  --radius-${name.slice(1)}: ${px}px;`),
    "",
    `  --shadow-float: ${shadowFloat.light};`,
    "",
    `  --ease-standard: cubic-bezier(${x1}, ${y1}, ${x2}, ${y2});`,
    ...Object.entries(motion.durationMs).map(
      ([name, ms]) => `  --duration-${name}: ${ms}ms;`,
    ),
    `  --rise-distance: ${motion.riseDistance}px;`,
  ];
  const dark = [...colorLines("dark"), `  --shadow-float: ${shadowFloat.dark};`];

  return [
    HEADER,
    "",
    "@theme {",
    ...theme,
    "}",
    "",
    ':root[data-theme="dark"] {',
    ...dark,
    "}",
    "",
  ].join("\n");
}
