/**
 * Copies the brand logos in this folder to every platform that shows them (decision 0003).
 * Each PNG here is named by its `BRAND_FAMILIES` id and is the only copy anyone edits.
 *
 * Outputs (all generated, never hand-edited):
 *   apps/ios/Resources/Assets.xcassets/BrandLogos/brand-{id}.imageset   iOS asset catalog
 *   packages/web/public/brand-logos/{id}.png                             web static files
 *   packages/web/src/components/brand/logos.ts                          ids that have a logo
 *
 * Run from the repository root:
 *   pnpm brand-logos            write the outputs
 *   pnpm brand-logos --check    exit 1 when any output is stale (CI)
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { BRAND_FAMILIES } from "../../packages/shared/src/brands";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");
const IOS_DIR = join(ROOT, "apps/ios/Resources/Assets.xcassets/BrandLogos");
const WEB_DIR = join(ROOT, "packages/web/public/brand-logos");
const WEB_TS = join(ROOT, "packages/web/src/components/brand/logos.ts");
const GENERATED = "Generated by design/brand-logos/generate.ts; do not edit by hand.";
const XCODE_INFO = { author: "xcode", version: 1 };

interface Output {
  path: string;
  contents: Buffer | string;
}

/** Logo ids in this folder, sorted; a file that names no brand family is an error. */
function logoIds(): string[] {
  const ids = readdirSync(HERE)
    .filter((file) => file.endsWith(".png"))
    .map((file) => file.slice(0, -".png".length))
    .sort();
  const known = new Set(BRAND_FAMILIES.map((family) => family.id));
  const unknown = ids.filter((id) => !known.has(id));
  if (unknown.length > 0) {
    throw new Error(`No brand family for ${unknown.join(", ")}: name each PNG by its BRAND_FAMILIES id.`);
  }
  return ids;
}

const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;

function webModule(ids: readonly string[]): string {
  return `// ${GENERATED}

/** Brand family ids with a logo at \`/brand-logos/{id}.png\` (decision 0003). */
export const BRAND_LOGO_IDS: ReadonlySet<string> = new Set(${JSON.stringify(ids)});

/** URL of the family's logo, or null when it has none and draws its monogram tile instead. */
export function brandLogoSrc(familyId: string): string | null {
  return BRAND_LOGO_IDS.has(familyId) ? \`/brand-logos/\${familyId}.png\` : null;
}
`;
}

function outputs(ids: readonly string[]): Output[] {
  const files: Output[] = [
    { path: join(IOS_DIR, "Contents.json"), contents: json({ info: XCODE_INFO, properties: { "provides-namespace": false } }) },
    { path: WEB_TS, contents: webModule(ids) },
  ];
  for (const id of ids) {
    const png = readFileSync(join(HERE, `${id}.png`));
    const imageset = join(IOS_DIR, `brand-${id}.imageset`);
    files.push(
      { path: join(imageset, `brand-${id}.png`), contents: png },
      { path: join(imageset, "Contents.json"), contents: json({ images: [{ filename: `brand-${id}.png`, idiom: "universal" }], info: XCODE_INFO }) },
      { path: join(WEB_DIR, `${id}.png`), contents: png },
    );
  }
  return files;
}

/** Generated entries left behind by a logo that no longer exists here. */
function strays(ids: readonly string[]): string[] {
  const keep = new Set(ids);
  const ios = existsSync(IOS_DIR)
    ? readdirSync(IOS_DIR)
        .filter((entry) => entry.startsWith("brand-") && entry.endsWith(".imageset"))
        .filter((entry) => !keep.has(entry.slice("brand-".length, -".imageset".length)))
        .map((entry) => join(IOS_DIR, entry))
    : [];
  const web = existsSync(WEB_DIR)
    ? readdirSync(WEB_DIR)
        .filter((entry) => !keep.has(entry.replace(/\.png$/, "")))
        .map((entry) => join(WEB_DIR, entry))
    : [];
  return [...ios, ...web];
}

function isCurrent(output: Output): boolean {
  if (!existsSync(output.path)) return false;
  const want = typeof output.contents === "string" ? Buffer.from(output.contents) : output.contents;
  return readFileSync(output.path).equals(want);
}

function main(): void {
  const check = process.argv.includes("--check");
  const ids = logoIds();
  const stale = outputs(ids).filter((output) => !isCurrent(output));
  const extra = strays(ids);
  const show = (path: string) => relative(ROOT, path);

  if (check) {
    if (stale.length === 0 && extra.length === 0) {
      console.log(`brand-logos: ${ids.length} logos in sync`);
      return;
    }
    for (const output of stale) console.error(`stale: ${show(output.path)}`);
    for (const path of extra) console.error(`not generated from design/brand-logos: ${show(path)}`);
    console.error("Run `pnpm brand-logos` and commit the result.");
    process.exit(1);
  }

  for (const output of stale) {
    mkdirSync(dirname(output.path), { recursive: true });
    writeFileSync(output.path, output.contents);
  }
  for (const path of extra) rmSync(path, { recursive: true });
  console.log(`brand-logos: ${ids.length} logos; wrote ${stale.length} files, removed ${extra.length}`);
}

main();
