import { AUSTRALIAN_STATES } from "./states";
import { DATA_SOURCES } from "./data-sources";

function swiftString(value: string | null): string {
  return value === null ? "nil" : JSON.stringify(value);
}

/** Swift source for the data-source table, so iOS credits each state exactly like web. */
export function emitDataSourcesSwift(): string {
  const rows = AUSTRALIAN_STATES.map((state) => {
    const s = DATA_SOURCES[state];
    return `        ${JSON.stringify(state)}: DataSource(name: ${swiftString(s.name)}, url: ${swiftString(s.url)}, note: ${swiftString(s.note)}, attributionTemplate: ${swiftString(s.attribution)}, reportURL: ${swiftString(s.reportUrl)}),`;
  });
  return `// Generated by @servo-map/shared (scripts/generate-swift.ts) from src/data-sources.ts. Do not edit.

import Foundation

/** Where a state's prices come from, and what its licence makes us show (decision 0007). */
public struct DataSource: Hashable, Sendable {
    /** The scheme's public name, credited on every price ("via NSW FuelCheck"). */
    public let name: String
    public let url: String
    /** One line on how the scheme reports. */
    public let note: String
    let attributionTemplate: String?
    /** Where people report a wrong or stale price, where the licence requires offering it. */
    public let reportURL: String?

    /** The statement the licence prescribes, dated \`year\`; nil when only credit is required. */
    public func attribution(year: Int) -> String? {
        attributionTemplate?.replacingOccurrences(of: "{year}", with: String(year))
    }

    /** Keyed by the API's state code ("nsw", "act", …). */
    public static let byState: [String: DataSource] = [
${rows.join("\n")}
    ]
}
`;
}
