import { BRAND_FAMILIES, type BrandFamily } from "./brands";

const GROUP_CASE: Record<BrandFamily["group"], string> = {
  major: "major",
  value: "value",
  members: "members",
  independent: "independent",
};

/** `0xRRGGBB` for a `#RRGGBB` colour. */
function hex(value: string): string {
  return `0x${value.slice(1).toUpperCase()}`;
}

function markSwift(f: BrandFamily): string {
  const { background, foreground, stripe } = f.mark;
  return `Mark(background: ${hex(background)}, foreground: ${hex(foreground)}, stripe: ${stripe ? hex(stripe) : "nil"})`;
}

function list(values: readonly string[]): string {
  return `[${values.map((v) => JSON.stringify(v)).join(", ")}]`;
}

/** Swift source for the brand-family table, so iOS resolves raw brand names exactly like web. */
export function emitBrandsSwift(): string {
  const families = BRAND_FAMILIES.map(
    (f) =>
      `        BrandFamily(id: ${JSON.stringify(f.id)}, name: ${JSON.stringify(f.name)}, seal: ${JSON.stringify(f.seal)}, group: .${GROUP_CASE[f.group]}, mark: ${markSwift(f)}, names: ${list(f.names)}, contains: ${list(f.contains ?? [])}),`,
  );
  return `// Generated by @servo-map/shared (scripts/generate-swift.ts) from src/brands.ts. Do not edit.

import Foundation

public struct BrandFamily: Identifiable, Hashable, Sendable {
    public enum Group: String, Sendable { case major, value, members, independent }

    /** The brand mark's colours as 0xRRGGBB; the same in light and dark, like a sign. */
    public struct Mark: Hashable, Sendable {
        public let background: UInt32
        public let foreground: UInt32
        public let stripe: UInt32?
    }

    public let id: String
    public let name: String
    public let seal: String
    public let group: Group
    public let mark: Mark
    let names: [String]
    let contains: [String]

    /** Every family in display order; the last is the Independent catch-all. */
    public static let all: [BrandFamily] = [
${families.join("\n")}
    ]

    /** Resolves a raw upstream brand name; unknown names fall back to Independent. */
    public static func resolve(_ raw: String) -> BrandFamily {
        let key = raw.trimmingCharacters(in: .whitespaces).lowercased()
        if let exact = all.first(where: { $0.names.contains(key) }) { return exact }
        if let partial = all.first(where: { family in family.contains.contains { key.contains($0) } }) { return partial }
        return all[all.count - 1]
    }
}
`;
}
