import { RENDERED_VEHICLE_IDS } from "./generated/car-renders";
import { CAR_IMAGE_DIR, DEFAULT_CAR_IMAGE_BODY, GENERIC_CAR_IMAGE_PREFIX } from "./vehicle-images";

/** Swift source for the car-picture rule, so iOS names a car's picture exactly like the Worker. */
export function emitVehicleImagesSwift(rendered: ReadonlySet<string> = RENDERED_VEHICLE_IDS): string {
  const ids = [...rendered].sort().map((id) => JSON.stringify(id));
  return `// Generated by @servo-map/shared (scripts/generate-swift.ts) from src/vehicle-images.ts. Do not edit.

import Foundation

/** Where a car's picture lives on the website (decision 0008), as \`vehicleImagePath\` in @servo-map/shared. */
public enum VehicleImage {
    /** Catalogue generations with a render of their own. */
    static let rendered: Set<String> = [${ids.join(", ")}]

    /**
     * Site path of the picture: the generation's own render when there is one, otherwise the
     * unbranded stand-in for its body type (the ${DEFAULT_CAR_IMAGE_BODY} when a hand-entered car has none).
     */
    public static func path(id: String?, body: String?) -> String {
        let name = id.flatMap { rendered.contains($0) ? $0 : nil } ?? "${GENERIC_CAR_IMAGE_PREFIX}\\(body ?? "${DEFAULT_CAR_IMAGE_BODY}")"
        return "${CAR_IMAGE_DIR}/\\(name).jpg"
    }
}
`;
}
