import { parseVehicles } from "./vehicles";

/** TypeScript module holding the parsed catalogue, so the Worker needs no file access at runtime. */
export function emitVehiclesModule(csv: string): string {
  const vehicles = parseVehicles(csv);
  return `// Generated by @servo-map/shared (scripts/generate-vehicles.ts) from data/vehicles.csv. Do not edit.
import type { Vehicle } from "../vehicles";

export const VEHICLES: readonly Vehicle[] = ${JSON.stringify(vehicles, null, 2)};
`;
}
