// Generated by design/brand-logos/generate.ts; do not edit by hand.

/** Brand family ids with a logo at `/brand-logos/{id}.png` (decision 0003). */
export const BRAND_LOGO_IDS: ReadonlySet<string> = new Set(["7-eleven","ampol","bp","caltex","liberty","metro","mobil","puma","shell","united"]);

/** URL of the family's logo, or null when it has none and draws its monogram tile instead. */
export function brandLogoSrc(familyId: string): string | null {
  return BRAND_LOGO_IDS.has(familyId) ? `/brand-logos/${familyId}.png` : null;
}
